# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Docker app to Azure Web App - ea-spring

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or whatever version you prefer

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend # Change to your frontend directory

      # Build the React app
      - name: Build React app
        run: npm run build-for-azure
        working-directory: ./frontend # Change to your frontend directory

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-spring-boot-app .

      # Log in to Azure Container Registry (if using ACR)
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY_NAME }} # Your ACR name
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }} # Your ACR username
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }} # Your ACR password

      # Push the Docker image to Azure Container Registry (if using ACR)
      - name: Push Docker image
        run: |
          docker tag my-spring-boot-app ${{ secrets.AZURE_REGISTRY_NAME }}/my-spring-boot-app:latest
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}/my-spring-boot-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "dev"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ea-spring" # Your Azure Web App name
          slot-name: "dev" # Deployment slot name
          images: ${{ secrets.AZURE_REGISTRY_NAME }}/my-spring-boot-app:latest # Docker image path
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_02C6BAF5E632449DA439FE494E136821 }}
