name: Build and Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      # Build the React app
      - name: Build React app
        run: npm run build-for-azure
        working-directory: ./frontend

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      # Build with Maven
      - name: Build with Maven
        run: mvn clean package

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: eaxpost
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: eaxpost/demo:latest

  azure_login:
    runs-on: ubuntu-latest
    environment: for-oicd
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Allows access to repository contents
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: 1036aa7e-0ac8-404a-86b3-64a6bb6ef749
          tenant-id: 99fe1041-ba57-4f49-866b-06c297c116cc
          allow-no-subscriptions: true

      - name: Print Azure Account Info
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account show
