# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - eerikanttila-spring

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "microsoft"

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: |
          BUILD_PATH=../src/main/resources/static npm run build || { echo "Frontend build failed"; exit 1; }
          echo "Frontend build completed. Listing directory contents:"
          ls -la ../src/main/resources/static  # List files to check if they exist

      - name: Prepare frontend build for upload
        run: |
          mkdir -p frontend-build
          cp -r ../src/main/resources/static/* frontend-build/ || { echo "No files found to copy"; exit 1; }

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: "${{ github.workspace }}/target/*.jar"

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend-build/** # Upload from the prepared directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "main"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "eerikanttila-spring"
          slot-name: "main"
          package: "*.jar"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C6AE559666A34B5CB73DA7E00D521A3A }}

      - name: Deploy frontend build
        run: |
          echo "Deploying frontend build..."
          az webapp deploy --name eerikanttila-spring --resource-group eerikanttila-sandbox-rg --src-path frontend-build --slot main --target-path /site/wwwroot/frontend --type zip
