name: build and deploy spring-api
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy spring-api
    runs-on: ubuntu-latest
    steps:
      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: eaxpost/rest-api:v1.0.0

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: eaxpost
          password: Dockerpassword12!

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: eaxpost/rest-api:v1.0.0
